package com.mario;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jaye' at '12/26/16 9:29 PM' with Gradle 2.10
 *
 * @author jaye, @date 12/26/16 9:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
