
import static junit.framework.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jaye' at '12/26/16 9:29 PM' with Gradle 2.10
 *
 * @author jaye, @date 12/26/16 9:29 PM
 */
public class LibraryTest {

    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
